### ISSUE TITLE
과제 check

### ISSUE THREAD

**Issue by seunghyun-24** [seunghyun-24/nest-study#45]
**1. DB schema 변경점 ** #32 
i) Club
- 정의: 클럽 정보를 관리하는 테이블.
- 필드:
- [ ] id: 클럽 ID 
- [ ] title: 클럽 이름
- [ ] leaderId: 클럽장 (유저 ID)
- [ ] description: 클럽 설명
- [ ] maxPeople: 클럽 최대 정원
- [ ] createdAt, updatedAt: 생성 및 업데이트 시간

ii) ClubJoin
- 정의: 클럽과 유저 간의 관계를 관리하는 테이블.
- 필드:
- [ ] id: 클럽join ID
- [ ] clubId: 클럽 ID
- [ ] userId: 유저 ID
- [ ] status: ClubJoinStatus (enum으로 클럽신청 리스트, 클럽 회원 리스트)
- [ ] createdAt, updatedAt: 생성 및 업데이트 시간

iii) user에 club, clubJoin 추가

iv) Event에 clubId, archived 추가
- 특정 모임이 클럽 전용인지 구분하기 위해 clubId  추가: null 지원 (일반 이벤트) 
- 클럽 삭제시 이미 이뤄진 클럽 모임 보존하기 위해 archived 추가 (클럽 삭제 시 클럽 모임 보존 위함)

v) ClubJoinStatus
- APPLICANT: 클럽 가입 신청자
- MEMBER: 클럽 멤버 (클럽 모임 이용 가능)
- REJECTED: 클럽 가입 거절자

** 클럽 과제 기능 별 API **
- [ ] 클럽은 특정 유저(클럽장)가 생성할 수 있다. #33 
- [ ] 클럽 전용 모임을 생성할 수 있다. 
- [ ] 클럽 전용 모임에 참여하는 건 클럽에 가입된 유저들만 가능하다. 
- [ ] 해당 유저들은 클럽 전용 모임에 리뷰를 생성, 조회, 삭제할 수 있다. #44 
- [ ] 일반 유저는 클럽 가입 신청을 할 수 있다. #37 
- [ ] 클럽장은 신청한 유저들의 리스트를 확인할 수 있다. #30 
- [ ] 클럽장은 신청한 유저들을 승인, 거절할 수 있다. #42
- [ ] 클럽 유저들은 클럽을 탈퇴할 수 있다. #41 
- [ ] 클럽 유저들은 클럽 전용 모임을 생성, 수정, 삭제할 수 있다.
- [ ] 클럽 유저들은 클럽 모임에 참여할 수 있다. #38 
- [ ] 클럽장은 클럽을 수정할 수 있다. + 클럽장을 위임할 수 있다. #34 
- [ ] 클럽장은 클럽을 삭제할 수 있다. #39
